CREATE TABLE [DBO].[User]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1), 
    [UniqueId] UNIQUEIDENTIFIER NULL CONSTRAINT DF_SERIALID DEFAULT NEWSEQUENTIALID(),
	[UserEmail] NVARCHAR(256) NOT NULL,
	[UserPassword] NVARCHAR(256) NOT NULL,
	[IsEmailVerified] BIT NOT NULL DEFAULT 0,
	[Activated] BIT NOT NULL DEFAULT 0,
	[ActivatedMachineKey] NVARCHAR (512) NULL,
	[ActivatedDateTime] DATETIME NULL,
	[MoreColumn1] BIT NULL,
	[MoreColumn2] DATETIME NULL,
	[MoreColumn3] BIT NULL,
	[MoreColumn4] DATETIME NULL,
	[MoreColumn5] DATETIME NULL,
	[DateTimeCreated] DATETIME DEFAULT GETDATE(),
	[DateTimeLastModified] DATETIME NULL
)