//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinglePcActivationDemo.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public long Id { get; set; }
        public Nullable<System.Guid> UniqueId { get; set; }
        public string UserEmail { get; set; }
        public string UserPassword { get; set; }
        public bool IsEmailVerified { get; set; }
        public bool Activated { get; set; }
        public string ActivatedMachineKey { get; set; }
        public Nullable<System.DateTime> ActivatedDateTime { get; set; }
        public Nullable<bool> MoreColumn1 { get; set; }
        public Nullable<System.DateTime> MoreColumn2 { get; set; }
        public Nullable<bool> MoreColumn3 { get; set; }
        public Nullable<System.DateTime> MoreColumn4 { get; set; }
        public Nullable<System.DateTime> MoreColumn5 { get; set; }
        public Nullable<System.DateTime> DateTimeCreated { get; set; }
        public Nullable<System.DateTime> DateTimeLastModified { get; set; }
    }
}
